-- 코드를 입력하세요
SELECT GOODS.USER_ID, GOODS.NICKNAME, SUM(BOARD.PRICE) AS TOTAL_SALES FROM USED_GOODS_BOARD BOARD
JOIN USED_GOODS_USER GOODS ON BOARD.WRITER_ID = GOODS.USER_ID
WHERE BOARD.STATUS = 'DONE'
GROUP BY GOODS.USER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES